import { Project, VariableDeclarationKind } from "ts-morph";
import { OpenAPISpec, Schema } from "@open-api-poc/open-api-validator";

export function gen(spec: OpenAPISpec, outdir: string) {
  const formatOptions = {
    indentMultiLineObjectLiteralBeginningOnBlankLine: true,
    ensureNewLineAtEndOfFile: true,
    indentSize: 2,
  };
  const project = new Project();

  const sourceFile = project.createSourceFile(`${outdir}/types.ts`, "", {
    overwrite: true,
  });

  sourceFile.addImportDeclaration({
    defaultImport: "z",
    moduleSpecifier: "zod",
  });

  // parameters
  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [
      _method,
      { operationId, parameters, requestBody },
    ] of Object.entries(methods)) {
      if (!parameters || parameters.length === 0) {
        continue;
      }

      let paramBuffer = "";

      parameters?.forEach((param) => {
        // TODO: Recursively build up the parameter types from  param.schema
        // TODO: Respect "required"
        paramBuffer = paramBuffer + `\n${param.name}: z.coerce.string(),`;
      });

      sourceFile
        .addVariableStatement({
          declarationKind: VariableDeclarationKind.Const,
          declarations: [
            {
              name: `${operationId}_Parameters`,
              initializer: `z.object({${paramBuffer}})`,
            },
          ],
        })
        .setIsExported(true);

      sourceFile.addTypeAlias({
        name: `${operationId}_Parameters`,
        type: `z.infer<typeof ${operationId}_Parameters>`,
        isExported: true,
      });

      if (requestBody) {
        for (const [contentType, { schema }] of Object.entries(
          requestBody.content
        )) {
          const contentBuffer = schemaToTypeString({ schema });

          sourceFile
            .addVariableStatement({
              declarationKind: VariableDeclarationKind.Const,
              declarations: [
                {
                  name: `${operationId}_RequestBody`,
                  initializer: `z.object({
                  content: z.record(
                    z.literal("${contentType}"),
                    ${contentBuffer}
                  )
                })`,
                },
              ],
            })
            .setIsExported(true);

          sourceFile.addTypeAlias({
            name: `${operationId}_RequestBody`,
            type: `z.infer<typeof ${operationId}_RequestBody>`,
            isExported: true,
          });
        }
      }
    }

    // responses
    for (const [_method, { operationId, responses }] of Object.entries(
      methods
    )) {
      for (const [status, { content }] of Object.entries(responses)) {
        for (const [contentType, { schema }] of Object.entries(content)) {
          const contentBuffer = schemaToTypeString({ schema });

          sourceFile
            .addVariableStatement({
              declarationKind: VariableDeclarationKind.Const,
              declarations: [
                {
                  name: `${operationId}_ResponseBody`,
                  initializer: `z.discriminatedUnion("status", [
                    z.object({
                      status: z.literal("${status}"),
                      content: z.record(
                        z.literal("${contentType}"),
                        ${contentBuffer}
                      ),
                    }),
                  ])`,
                },
              ],
            })
            .setIsExported(true);

          sourceFile.addTypeAlias({
            name: `${operationId}_ResponseBody`,
            type: `z.infer<typeof ${operationId}_ResponseBody>`,
            isExported: true,
          });
        }
      }
    }
  }

  sourceFile.insertText(
    0,
    `// This file is auto-generated by <your tool name>.
  // Changes to this file may be overwritten.

  `
  );

  sourceFile.formatText(formatOptions);
  sourceFile.saveSync();
}

function walkSchemaProp({
  prop,
  schema,
}: {
  prop: string;
  schema: Schema;
}): string {
  let buffer = "";
  if (schema.type === "object") {
    buffer = `${prop}: z.object({`;
    for (const [innerProp, propSchema] of Object.entries(
      schema?.properties || {}
    )) {
      buffer += walkSchemaProp({ prop: innerProp, schema: propSchema });
    }
    buffer += "\n}),";
    return buffer;
  }

  // TODO: Write a proper transform function
  // TODO: Take "required" into account
  buffer += `${prop}: z.coerce.${schema.type}(),`;

  return buffer;
}

function schemaToTypeString({ schema }: { schema: Schema }): string {
  let buffer = "z.object({\n";
  for (const [prop, propSchema] of Object.entries(schema?.properties || {})) {
    if (schema.properties) {
      buffer += walkSchemaProp({ prop, schema: propSchema });
      continue;
    }

    // TODO: Write a proper transform function
    // TODO: Take "required" into account
    buffer += `z.coerce.${schema.type}()`;
  }

  buffer += "\n})";

  return buffer;
}