import { Project, VariableDeclarationKind } from "ts-morph";
import { OpenAPISpec } from "@open-api-poc/open-api-validator";

export function gen(spec: OpenAPISpec, outdir: string) {
  const formatOptions = {
    indentMultiLineObjectLiteralBeginningOnBlankLine: true,
    ensureNewLineAtEndOfFile: true,
    indentSize: 2,
  };
  const project = new Project();

  const sourceFile = project.createSourceFile(`${outdir}/types.ts`, "", {
    overwrite: true,
  });

  sourceFile.addImportDeclaration({
    defaultImport: "z",
    moduleSpecifier: "zod",
  });

  // parameters
  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [_method, { operationId, parameters }] of Object.entries(
      methods
    )) {
      let paramBuffer = "";

      parameters?.forEach((param) => {
        // TODO: Recursively build up the parameter types from  param.schema
        paramBuffer = paramBuffer + `\n${param.name}: z.coerce.string(),`;
      });

      sourceFile
        .addVariableStatement({
          declarationKind: VariableDeclarationKind.Const,
          declarations: [
            {
              name: `${operationId}_Parameters`,
              initializer: `z.object({${paramBuffer}})`,
            },
          ],
        })
        .setIsExported(true);

      sourceFile.addTypeAlias({
        name: `${operationId}_Parameters`,
        type: `z.infer<typeof ${operationId}_Parameters>`,
        isExported: true,
      });
    }

    // responses
    for (const [_method, { operationId, responses }] of Object.entries(
      methods
    )) {
      for (const [status, { content }] of Object.entries(responses)) {
        for (const [contentType, { schema }] of Object.entries(content)) {
          let contentBuffer = "";
          for (const [prop, { type }] of Object.entries(schema.properties)) {
            // TODO: Recursively build up the parameter types from  param.schema
            contentBuffer = contentBuffer + `${prop}: z.coerce.${type}(),`;
          }

          sourceFile
            .addVariableStatement({
              declarationKind: VariableDeclarationKind.Const,
              declarations: [
                {
                  name: `${operationId}_ResponseBody`,
                  initializer: `z.discriminatedUnion("status", [
                    z.object({
                      status: z.literal("${status}"),
                      content: z.record(
                        z.literal("${contentType}"),
                        z.object({
                          ${contentBuffer}
                        })
                      ),
                    }),
                  ])`,
                },
              ],
            })
            .setIsExported(true);

          sourceFile.addTypeAlias({
            name: `${operationId}_ResponseBody`,
            type: `z.infer<typeof ${operationId}_ResponseBody>`,
            isExported: true,
          });
        }
      }
    }
  }

  sourceFile.insertText(
    0,
    `// This file is auto-generated by <your tool name>.
  // Changes to this file may be overwritten.

  `
  );

  sourceFile.formatText(formatOptions);
  sourceFile.saveSync();
}
