openapi: 3.0.0
info:
  title: Kitchen Sink Service
  version: 0.0.0
tags: []
paths:
  /healthz:
    get:
      operationId: healthz
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required:
                  - status
  /hello/{name}:
    get:
      operationId: hello
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
    post:
      operationId: updateHello
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                greeting:
                  type: string
              required:
                - greeting
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  envelope:
                    type: object
                    properties:
                      echo:
                        type: string
                    required:
                      - echo
                required:
                  - envelope
components: {}
